spring:
  flyway:
    placeholders:
      role:
        user: user
        moderator: moderator
        admin: admin
        superuser: superuser
      superuser:
        username: superuser
        password-hash: $2a$10$rI7UAUIq8zUWo2x1uElO..dosFRWT4wZnEGypNd5Aql908E1MvZiO #the password value is 'superuser'
        email: a@a.com
        first-name: Super
        last-name: User

logging:
  level:
    ROOT: INFO
    com.lazydev.stksongbook.webapp: DEBUG

storage:
  location: ./storage

security:
  authentication:
    jwt:
      secret: 55d3de79e7b18c67f42f420e9065b980bba03659
      # Token is valid 24 hours
      token-validity-in-seconds: 86400
      token-validity-in-seconds-for-remember-me: 2592000
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "Authorization,Link,X-Total-Count"
    allow-credentials: true
    max-age: 1800

application:
  gui-base-url: http://localhost:4200
